config/routes.rb
Rails.application.routes.draw do
  root 'speedtests#new'

  resource :speedtest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/speedtests_controller.rb
class SpeedtestsController < ApplicationController
  def new
    @file_url = ENV['SPEEDTEST_FILE']
  end

  def create
    Rails.logger.silence do
      head 200
    end
  end

  def show
    send_file Rails.root.join('public', ENV['SPEEDTEST_FILE'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpSpeedtestRb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/speedtests/new.html.erb
<h1>Network speed test</h1>
<%= hidden_field_tag :speedtest_download_url, speedtest_path %>
<%= hidden_field_tag :speedtest_upload_url, speedtest_path %>
<%= hidden_field_tag :speedtest_storage_url, @file_url %>

<%= form_with class: 'speedtest-weight-form' %>
<div class="control-group">
  <div id="speedtest-runner" class="btn btn-primary">Run</div>
</div>
<div id="speedtest-results" class="hide">
  <dl class="dl-horizontal">
    <dt>User IP</dt>
    <dd><%= request.remote_ip %></dd>
    <h3>Results</h3>
    <dt>Download speed</dt>
    <dd>
      <span class="speedtest-download-speed"></span>
      <span class="speedtest-download-speed-error text-error hide">request error</span>
    </dd>
    <dt>Upload speed</dt>
    <dd>
      <span class="speedtest-upload-speed"></span>
      <span class="speedtest-upload-speed-error text-error hide">request error</span>
    </dd>
    <dt>Storage download speed</dt>
    <dd>
      <span class="speedtest-image-storage-speed"></span>
      <span class="speedtest-image-storage-speed-error text-error hide">request error</span>
    </dd>
  </dl>
</div>
<div id="speedtest-execution">
  <input id="toggle-execution" type="checkbox" class="hide">
  <label class="showing-execution btn-link" for="showing-execution"></label>
  <div class="execution-text"></div>
</div>